import type { Database } from './database'

// Row type flows from `src/types/database.ts` (generated by `supabase gen types`).
// ProfileRole narrows the `role` column — the generated schema models it as a
// plain `string` because Postgres CHECK constraints aren't projected into the
// type system. Update this union when the CHECK changes.

export type ProfileRole = 'admin' | 'ventas'

export type Profile = Omit<Database['public']['Tables']['profiles']['Row'], 'role'> & {
  role: ProfileRole
}
