#!/usr/bin/env bash
#
# Regenerate src/types/database.ts from the linked Supabase project.
#
# Used by `npm run db:types`. Run this after every `supabase db push` so the
# generated Database type stays in sync with the live schema. The CI
# workflow does not regenerate on its own (yet — see the follow-up ticket
# for migration-PR drift detection), so this is the contract today.
#
# Environment:
#   SUPABASE_PROJECT_ID  Override the project ref. Defaults to staging.

set -euo pipefail

PROJECT_ID="${SUPABASE_PROJECT_ID:-comfhqhigiighmwuxfbb}"
OUTPUT="src/types/database.ts"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# stderr gets discarded to keep the CLI's "new version available" banner
# from polluting the generated file (it's been a footgun before).
supabase gen types typescript \
  --project-id "$PROJECT_ID" \
  --schema public \
  2>/dev/null > "$TMP"

{
  printf '// AUTOGENERATED FILE — do not edit by hand.\n'
  printf '// Regenerate with `npm run db:types` after every migration.\n'
  printf '// Source: Supabase project %s (staging by default).\n\n' "$PROJECT_ID"
  cat "$TMP"
} > "$OUTPUT"

echo "Regenerated $OUTPUT from project $PROJECT_ID"
